
export const MOSTRAR_FORMULARIO_LOGIN = 'MOSTRAR_FORMULARIO_LOGIN'
export const OBTENER_LOGIN = 'OBTENER_LOGIN'
export const MOSTRAR_TERMINOS_CONDICIONES_DATA_LOGIN = 'MOSTRAR_TERMINOS_CONDICIONES_DATA_LOGIN'